create table if not exists public.game_infos (
  id bigint generated by default as identity primary key,
  game_name text not null,
  genre text not null default '미확인',
  release_country text not null,
  game_release_date date,
  created_at timestamptz not null default now(),
  unique (game_name, release_country)
);

create table if not exists public.game_daily_rankings (
  id bigint generated by default as identity primary key,
  market_country text not null check (market_country in ('KR', 'JP', 'US')),
  collected_at timestamptz not null,
  ranking_date date not null,
  rank smallint not null check (rank between 1 and 100),
  game_id bigint not null references public.game_infos (id),
  rank_change smallint not null default 0,
  created_at timestamptz not null default now(),
  unique (market_country, ranking_date, rank)
);

create index if not exists game_daily_rankings_latest_idx
  on public.game_daily_rankings (market_country, collected_at desc, rank asc);

create index if not exists game_daily_rankings_trend_idx
  on public.game_daily_rankings (market_country, game_id, ranking_date asc);

alter table public.game_infos enable row level security;
alter table public.game_daily_rankings enable row level security;

create policy "Allow public read game infos"
  on public.game_infos
  for select
  using (true);

create policy "Allow public read daily rankings"
  on public.game_daily_rankings
  for select
  using (true);
